language: cpp
sudo: required
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
# Install dependencies
install:
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
branches:
  only:
  - master
 notifications:
  email: false