language: cpp
sudo: required
compiler:
  - gcc
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" -a "$CPP14" == "0" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
# Install dependencies
install:
  - sudo apt-get install -qq g++-4.8; fi
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
branches:
  only:
  - master
 notifications:
  email: false